### ISSUE TITLE
login failure

### ISSUE THREAD

**Issue by ellymakuba** [APHL-Global-Health/BLIS#7]
I have followed steps 1-7 in installing this application to my laptop running ubuntu. I have the login in screen but nothing happens when i click the Login button even if the username and passwords fields are empty.

**Comment by mapesa** [comment]
Hi @ellymakuba 

I'd suspect either permissions or some missing PHP module.

Check your web-server log and also the laravel log (app/storage/logs/laravel.log) for hints on what could be wrong. If you share the logs I'll be happy to help you get started.

**Comment by ellymakuba** [comment]
Thanks Mapesa, 
I managed to solve it, I had wrong configurations in my apache config file.

**Comment by mapesa** [comment]
Cool. Welcome to the BLIS community. I look forward to your contributions.
